# Default values for waldur.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:
  homeport: 1
  api: 1
  worker: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

apiScheme: "http"
homeportScheme: "http"
apiHostname: waldur.local
homeportHostname: waldur.local

affinity: {}

apiResources: {}
workerResources: {}
homeportResources: {}
beatResources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after '*resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

hpa:
  api:
    enabled: false
    resources:
      requests:
        cpu: 500m
    cpuUtilizationBorder: 70
  celery:
    enabled: false
    workerResources:
      requests:
        cpu: 2000m
    beatResources:
      requests:
        cpu: 300m
    cpuUtilizationBorder: 80

nodeSelector: {}

tolerations: []

service:
  type: ClusterIP
  port: 80

storageClassName: local-storage

ingress:
  tls:
    enabled: false
    source: "secret" # Possible values: `letsEncrypt` and `secret`
    customMastermindSecretName: ""
    customHomeportSecretName: ""
    secretsDir: "tls"  # Enabled only if source == `secret`
  whitelistSourceRange: '' # E.g. '192.168.22.0/24'
  whitelistSourceRangeAdmin: ''

celery:
  worker:
    enabled: true

proxy:
  httpsProxy: ""
  httpProxy: ""
  noProxy: ""

# overrides hostAliases in the Waldur deployment's pods
hostAliases: []
  # - ip: "1.2.3.4"
  #   hostnames:
  #     - "my.host.com"

waldur:
  imageName: "opennode/waldur-mastermind"
  imageTag: "6.7.1"
  initdbEnabled: true
  initdbImageName: "bitnami/postgresql"
  pullPolicy: Always
  secretKey: "SecretKeyChangeMe"
  supportToken: ""
  staffToken: ""
  debug: false
  mail:
    host: ""
    port: ""
    username: ""
    password: ""
    useTLS: "false"
    useSSL: "false"
    from: ""
    hookFrom: ""
    replyTo: ""
  notificationSubject: ""
  timeZone: "UTC"
  features: []
  currencyName: "EUR"
  mastermindUrl: ""
  site:
    name: "Waldur"
    logo: ""
    address: ""
    email: ""
    phone: ""
  defaultLanguage: "en"
  languageChoices:
    - en
    - et
    - lt
    - lv
    - ru
    - it
    - de
    - da
    - sv
    - es
    - fr
    - nb
    - ar
    - cs
  authMethods:
    - LOCAL_SIGNIN
  socialAuthMethods: []
  localIdp:
    name: ""
    label: ""
    managementUrl: ""
    protectedFields: []
  defaultIdp: ""
  keycloak_sync:
    enabled: false
    base_url: "http://localhost:8080/auth"
    realm: "waldur"
    client_id: "waldur"
    client_secret: "waldur"
    username: "admin"
    password: "secret"
  remoteEduteams:
    refreshToken: ""
    clientID: ""
    clientSecret: ""
    userinfoUrl: ""
    tokenUrl: ""
    sshApiUrl: ""
    sshApiUsername: ""
    sshApiPassword: ""
    enableSync: false
  ldap:
    host: ""
    baseDN: ""
    userDN: ""
    user: ""
    password: ""
    admins: ""
    support: ""
  freeipa:
    hostname: ""
    password: ""
    username: ""
    verifySSL: ""
    groupnamePrefix: ""
    usernamePrefix: ""
  valimo:
    dir: "waldur_valimo"
    valimoClientKey: ""
    valimoClientCrt: ""
    apId: ""
    apPwd: ""
    dnsname: ""
    url: ""
    signatureProfile: ""
    label: ""
    mobilePrefix: ""
    managementUrl: ""
    protectedFields: []
  paypal:
    secret: ""
    clientId: ""
  invoice:
    company: ""
    address: ""
    country: ""
    email: ""
    postalCode: ""
    phoneCountryCode: ""
    phoneNationalNumber: ""
    bank: ""
    bankAccount: ""
    vatCode: ""
    paymentInterval: ""
  invoice_reporting:
    enabled: false
    email: ""
    sap_params:
      km_kood: ""
      org_code: ""
      makset: ""
      funka: ""
      fund: ""
      eeluks: ""
      kuluuksus: ""
  slurm:
    customerPrefix: ""
    projectPrefix: ""
    allocationPrefix: ""
  support:
    backend: "zammad" # Can be "atlassian", "zammad" or "smax"
    atlassian:
      servicedeskEmail: ""
      servicedeskToken: ""
      servicedeskUsername: ""
      servicedeskPassword: ""
      servicedeskUrl: ""
      skipVerify: false
      organizationField: ""
      projectKey: ""
      useAutomaticRequestMapping: true
      legacy: false
    zammad:
      apiUrl: ""
      token: ""
      group: ""
      articleType: "email"
      commentCooldownDuration: 5
    smax:
      apiUrl: ""
      tenantId: ""
      login: ""
      password: ""
      organisationField: ""
      projectField: ""
      affectedResourceField: ""
      timesToPull: 10
      secondsToWait: 1
      creationSourceName: ""
      verifySSL: True
  marketplace:
    notify_staff: false
    script:
      enabled: false
      dockerImages: {}
      kubeconfigPath: "k8s/kubeconfig"
      kubeconfig: ""
      k8sNamespace: "default"
      jobTimeout: 1800
  pid_datacite:
    repository_id: ""
    password: ""
    prefix: ""
    url: ""
    publisher: ""
    collection_doi: ""
  sentryDSN: ""
  whitelabeling:
    # Icons mount at /etc/waldur/icons, thus the path to logo should contain:
    # /etc/waldur/icons/ plus the name of the file as specified in icons-config.yaml configmap
    # see test/values.yaml for working examples
    shortPageTitle: ""
    modePageTitle: ""
    loginLogoPath: ""
    sidebarLogoPath: ""
    poweredByLogoPath: ""
    faviconPath: ""
    tosHtmlPath: ""
    brandColor: ""
    brandLabelColor: ""
    heroImagePath: ""
    heroLinkLabel: ""
    heroLinkUrl: ""
    privacyHtmlPath: ""
    siteDescription: ""
    supportPortalLink: ""
    tosHtml: ""
    privacyHtml: ""
  invitationWebhookUrl: ""
  enableStrictCheckAcceptingInvitation: false
  # Measured in weeks number
  invitationDuration:
    individual: 1
    group: 1
  mastermindTemplating:
    mastermindTemplatesPath: "mastermind_templates/mastermind-templates.yaml"
    mastermindTemplates: {}
  notifications: []
  saml2:
    dir: "waldur_saml2"
    federations: []
  ssh_public_key_path: ""
  ssh_private_key_path: ""
  ssh_public_key: ""
  ssh_private_key: ""
  homeport:
    imageName: "opennode/waldur-homeport"
    matomoUrlBase: ""
    matomoSiteId: ""
    userMandatoryFields: {}
    userRegistrationHiddenFields: {}
    docsLink: "https://docs.waldur.com"
    invitationCivilCodeHelpText: ""
  metricsExporter:
    enabled: false
    includeAnnotations: true
  uvkEverypay:
    enabled: false
    imageTag: latest
    uvkServer: "https://uvk-test.ut.ee/client/a74/server.php?format=JSON&action=uvk__"
    everypayGateway: "https://igw-demo.every-pay.com/api/v4"
    everypayUsername: ""
    everypayPassword: ""
    azureTenantID: ""
    azureClientID: ""
    azureClientSecret: ""
    azureScope: ""

bootstrap:
  enabled: false
  script: "bootstrap.sh"
  dir: "bootstrap"

externalDB:
  enabled: false
  flavor: "zalando"
  secretName: "waldur.waldur.credentials.postgresql.acid.zalan.do"
  serviceName: "waldur-postgres"

postgresql:
  enabled: false
  auth:
    username: "waldur"
    password: "waldur"
    database: "waldur"
  # The values are in use only if postgresql.enabled = true
  primary:
    persistence:
      size: "10Gi"
    resources:
      requests:
        memory: "1024Mi"
        cpu: "500m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"
  image:
    registry: "docker.io"
    tag: 12
  metrics:
    enabled: false

postgresqlha:
  enabled: false
  postgresql:
    database: waldur
    username: waldur
    password: waldur
    postgresPassword: postgres
    repmgrPassword: repmgr
    replicaCount: 3
    image:
      tag: "12.15.0-debian-11-r12"
  pgpool:
    image:
      tag: "4.4.3-debian-11-r6"

postgresBackup:
  enabled: false
  schedule: "0 5 * * *"
  rotationSchedule: "0 6 * * 6"
  maxNumber: 10
  image: opennode/postgres-minio:0.1.0
  name: "waldur"

minio:
  accessKey: ""
  secretKey: ""
  bucketName: data
  ## min.io service endpoint used for communication inside a cluster
  endpoint: "http://minio.default.svc.cluster.local:9000" ## See docs/service-endpoint.md for details.

rabbitmq:
  enabled: false
  auth:
    username: "waldur"
    password: "waldur"
  # The values are in use only if rabbitmq.enabled = true
  image:
    registry: "docker.io"
    repository: "bitnami/rabbitmq"
    tag: 3.8.14
  replicaCount: 3
  persistence:
    enabled: true
    size: "10Gi"
    storageClass: ""
  clustering:
    forceBoot: true
  # hostname of rabbitmq service, respected only if rabbitmq.enabled = false and RMQ release is deployed separately
  host: "rmq-rabbitmq"

stressTesting:
  enabled: false
  locustFilePath: "locust_task/locust_test.py"

global:
  imageRegistry: "docker.io"
