name: Release Helm Charts
on:
  push:
    branches:
      - devel

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run chart-releaser job
        uses: helm/chart-releaser-action@v1.4.0
